# Generated by Django 3.2.5 on 2021-07-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_model',
        ),
    ]
